default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { 'root' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { '' } %>
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>

development:
  <<: *default
  database: rails_for_learning_development

test:
  <<: *default
  database: rails_for_learning_test

production:
  <<: *default
  database: rails_for_learning_production
